version: '3.8'

services:  
  
  postgresql:
    image: postgres:14
    hostname: postgresql
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "dmbat_uzasbo2_159"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor-console:
    image: conduktor/conduktor-console:1.23.0
    ports:
      - "8080:8080"
    volumes:
      - conduktor_data:/var/conduktor
      - ./etc/secrets/conduktor_jaas.conf:/etc/kafka/conduktor_jaas.conf
    environment:
      CDK_DATABASE_URL: "postgresql://conduktor:dmbat_uzasbo2_159@postgresql:5432/conduktor-console"
      CDK_CLUSTERS_0_ID: "default"
      CDK_CLUSTERS_0_NAME: "My Local Kafka Cluster"
      CDK_CLUSTERS_0_COLOR: "#0013E7"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:19092
      CDK_CLUSTERS_0_SCHEMAREGISTRY_URL: "http://schemaregistry:8081"
      CDK_CLUSTERS_0_KAFKACONNECTS_0_URL: "http://kafka-connect:8083"
      CDK_CLUSTERS_0_KAFKACONNECTS_0_NAME: "full stack kafka connect"
      #CDK_CONSUMER_CONFIG: "-Djava.security.auth.login.config=/etc/kafka/conduktor_jaas.conf"
    depends_on:
      - postgresql

volumes:
  pg_data: {}
  conduktor_data: {}
